# Generated by Django 4.2.4 on 2023-08-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('fileupload', models.ImageField(upload_to='')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
