# Generated by Django 4.2.4 on 2023-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('cmpname', models.CharField(max_length=30)),
                ('qty', models.IntegerField()),
                ('expdate', models.DateField()),
                ('desc', models.CharField(max_length=80)),
            ],
        ),
    ]
