# Generated by Django 4.2.4 on 2023-08-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_alter_fileupload_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='fileupload',
            field=models.FileField(upload_to='djangoapp/static'),
        ),
    ]
