# Generated by Django 4.2.4 on 2023-08-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_alter_fileupload_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileuploadtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('fileupload', models.FileField(upload_to='djangoapp/static')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
