# Generated by Django 4.2.4 on 2023-08-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_fileuploadtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadall_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(max_length=30)),
                ('audio_file', models.FileField(upload_to='djangoapp/static')),
                ('video_name', models.CharField(max_length=30)),
                ('video_file', models.FileField(upload_to='djangoapp/static')),
                ('pdf_name', models.CharField(max_length=30)),
                ('pdf_file', models.FileField(upload_to='djangoapp/static')),
            ],
        ),
    ]
