# Generated by Django 4.2.4 on 2023-08-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_uploadall_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkbox_select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('kerala', 'kerala'), ('tamil nadu', 'tamil nadu'), ('karnataka', 'karnataka')], max_length=20)),
                ('english', models.BooleanField(default=False)),
                ('malayalam', models.BooleanField(default=False)),
                ('hindi', models.BooleanField(default=False)),
            ],
        ),
    ]
